# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2.0'
    - name: Put current date into a variable
      run: |
        $NOW=& Get-Date -format yyyy-MM-dd
        echo "NOW=$NOW" >> $env:GITHUB_ENV
      env:
        RESULT_BUNDLE: "CodeCoverage${{env.NOW}}.xcresult"
        RESULT_JSON: "CodeCoverage${{env.NOW}}.json"   
    # - name: Build
    #   run: |
    #     xcodebuild build -project NYTimes.xcodeproj -scheme NYTimes clean build -sdk iphonesimulator CODE_SIGNING_ALLOWED=No
    - name: Run tests
      run: |
        xcodebuild -project NYTimes.xcodeproj -scheme NYTimes -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14' -enableCodeCoverage YES -resultBundlePath $RESULT_BUNDLE clean build test
    - name: Generate coverage reports to json format
      run: |
        xcrun xccov view --report --json $RESULT_BUNDLE > $RESULT_JSON
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
